require:
  - rubocop-rspec
  - rubocop-faker

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

Metrics/AbcSize: { Enabled: false }
Metrics/MethodLength: { Max: 15 }

Style/Documentation: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/HashSyntax:
  EnforcedShorthandSyntax: either
Style/MixinUsage:
  Exclude:
    - "spec/**/*"

RSpec/DescribeClass: { Enabled: false }
RSpec/ExampleLength: { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }
